insert into bands (name, metal_archives_id) values('Achelous', 3540381725);
insert into bands (name, metal_archives_id) values('Amon Amarth', 150);
insert into bands (name, metal_archives_id) values('Astarte', 2233);
insert into bands (name, metal_archives_id) values('Avantasia', 331);
insert into bands (name, metal_archives_id) values('Bathory', 184);
insert into bands (name, metal_archives_id) values('Battle Beast', 3540325827);
insert into bands (name, metal_archives_id) values('Battleroar', 5121);
insert into bands (name, metal_archives_id) values('Blind Guardian', 3);
insert into bands (name, metal_archives_id) values('Bolt Thrower', 234);
insert into bands (name, metal_archives_id) values('Burning Witches', 3540420779);
insert into bands (name, metal_archives_id) values('Civil War', 3540355146);
insert into bands (name, metal_archives_id) values('Cradle of Filth', 24);
insert into bands (name, metal_archives_id) values('Crystal Viper', 33867);
insert into bands (name, metal_archives_id) values('Demons & Wizards', 158);
insert into bands (name, metal_archives_id) values('Dimmu Borgir', 69);
insert into bands (name, metal_archives_id) values('Doomsword', 734);
insert into bands (name, metal_archives_id) values('Edguy', 170);
insert into bands (name, metal_archives_id) values('Emerald Sun', 37365);
insert into bands (name, metal_archives_id) values('Falkenbach', 1071);
insert into bands (name, metal_archives_id) values('Gamma Ray', 221);
insert into bands (name, metal_archives_id) values('Ghost', 3540309157);
insert into bands (name, metal_archives_id) values('Grand Magus', 7162);
insert into bands (name, metal_archives_id) values('Grave Digger', 391);
insert into bands (name, metal_archives_id) values('Hammer King', 3540395840);
insert into bands (name, metal_archives_id) values('Helloween', 159);
insert into bands (name, metal_archives_id) values('Hysterica', 89238);
insert into bands (name, metal_archives_id) values('Iced Earth', 4);
insert into bands (name, metal_archives_id) values('Infidel', 82893);
insert into bands (name, metal_archives_id) values('Innerwish', 14916);
insert into bands (name, metal_archives_id) values('Iron Savior', 329);
insert into bands (name, metal_archives_id) values('Jon Schaffers Purgatory', 8021);
insert into bands (name, metal_archives_id) values('Judas Priest', 97);
insert into bands (name, metal_archives_id) values('Kamelot', 166);
insert into bands (name, metal_archives_id) values('KKs Priest', 3540495587);
insert into bands (name, metal_archives_id) values('Manowar', 83);
insert into bands (name, metal_archives_id) values('Metallica', 125);
insert into bands (name, metal_archives_id) values('Morgana Lefay', 1453);
insert into bands (name, metal_archives_id) values('Necromantia', 927);
insert into bands (name, metal_archives_id) values('Nightwish', 39);
insert into bands (name, metal_archives_id) values('Numenor', 3540290774);
insert into bands (name, metal_archives_id) values('Powerstorm', 9886);
insert into bands (name, metal_archives_id) values('Rebellion', 967);
insert into bands (name, metal_archives_id) values('Rotting Christ', 314);
insert into bands (name, metal_archives_id) values('Running Wild', 306);
insert into bands (name, metal_archives_id) values('Sabaton', 484);
insert into bands (name, metal_archives_id) values('Sakis Tolis', 3540503178);
insert into bands (name, metal_archives_id) values('Virgin Steele', 105);
insert into bands (name, metal_archives_id) values('Warkings', 3540447358);
insert into bands (name, metal_archives_id) values('White Skull', 902);
insert into bands (name, metal_archives_id) values('Wizard', 156);